export const SELECT_CLIENT = 'SELECT_CLIENT';
export const SELECT_PRODUCTS = 'SELECT_PRODUCTS';
export const AMOUNT_PRODUCTS = 'AMOUNT_PRODUCTS';
export const UPDATE_TOTAL_PAYMENT = 'UPDATE_TOTAL_PAYMENT';
export const RESET_STATES = 'RESET_STATES';
